import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Header, MenuItem } from "@/components/TopNav/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// menu list
const menuList: MenuItem[] = [
  { label: "Home", link: "/", active: true },
  { label: "About", link: "/about", active: false },
  { label: "Contact", link: "/contact", active: false },
];


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex flex-col w-full">
            <div>
              <Header menuList={menuList} />
            </div>
            <div>{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
